{"historyId": "ef522e1a46908b98aa0b89b1f6d42f7f", "status": "failed", "stop": 1604965712372, "statusDetails": {"trace": "def test_failure():\n>       assert False\nE       assert False\n\npy_practice\\py_allure_p.py:11: AssertionError", "message": "AssertionError: assert False"}, "testCaseId": "6b5468f4d278ea153ea5335a87add1b3", "name": "test_failure", "labels": [{"name": "parentSuite", "value": "py_practice"}, {"name": "suite", "value": "py_allure_p"}, {"name": "host", "value": "LAPTOP-6QKFPKJ6"}, {"name": "thread", "value": "20684-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "py_practice.py_allure_p"}], "fullName": "py_practice.py_allure_p#test_failure", "start": 1604965712372, "uuid": "24ffae85-7313-4c65-ad40-bcb7d54f2855"}