{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception(\"oops\")\nE       Exception: oops\n\npy_practice\\test_alluremode.py:17: Exception"}, "start": 1605137344162, "stop": 1605137344163, "uuid": "3259bad7-e41d-4600-a284-01df15bf19f1", "historyId": "7b69f26bddf363982f842cc3ad7d85f8", "testCaseId": "df9add288873f3b6bce5d13274225680", "fullName": "py_practice.test_alluremode#test_broken", "labels": [{"name": "parentSuite", "value": "py_practice"}, {"name": "suite", "value": "test_alluremode"}, {"name": "host", "value": "LAPTOP-6QKFPKJ6"}, {"name": "thread", "value": "10128-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "py_practice.test_alluremode"}]}