{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n>       assert False\nE       assert False\n\npy_practice\\test_alluremode.py:11: AssertionError"}, "start": 1605137343984, "stop": 1605137343985, "uuid": "28928acc-163e-4fc5-8a44-4c4cfe609514", "historyId": "e6b0fc4e5a497547205355ce403362f5", "testCaseId": "839717bf706739e2699060c6907cbeae", "fullName": "py_practice.test_alluremode#test_failure", "labels": [{"name": "parentSuite", "value": "py_practice"}, {"name": "suite", "value": "test_alluremode"}, {"name": "host", "value": "LAPTOP-6QKFPKJ6"}, {"name": "thread", "value": "10128-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "py_practice.test_alluremode"}]}