{"fullName": "py_practice.test_alluremode#test_failure", "name": "test_failure", "historyId": "e6b0fc4e5a497547205355ce403362f5", "stop": 1605049795980, "testCaseId": "839717bf706739e2699060c6907cbeae", "statusDetails": {"trace": "def test_failure():\n>       assert False\nE       assert False\n\npy_practice\\test_alluremode.py:11: AssertionError", "message": "AssertionError: assert False"}, "uuid": "0cd35663-2bd9-400c-8b18-b1b1c1338917", "start": 1605049795979, "labels": [{"name": "parentSuite", "value": "py_practice"}, {"name": "suite", "value": "test_alluremode"}, {"name": "host", "value": "LAPTOP-6QKFPKJ6"}, {"name": "thread", "value": "18172-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "py_practice.test_alluremode"}], "status": "failed"}