{"statusDetails": {"trace": "def test_failure():\n>       assert False\nE       assert False\n\npy_practice\\py_allure_p.py:11: AssertionError", "message": "AssertionError: assert False"}, "start": 1605011566902, "uuid": "d9640e4c-6e31-4c74-b0c1-d9b8058aacce", "fullName": "py_practice.py_allure_p#test_failure", "historyId": "ef522e1a46908b98aa0b89b1f6d42f7f", "labels": [{"value": "py_practice", "name": "parentSuite"}, {"value": "py_allure_p", "name": "suite"}, {"value": "LAPTOP-6QKFPKJ6", "name": "host"}, {"value": "17056-MainThread", "name": "thread"}, {"value": "pytest", "name": "framework"}, {"value": "cpython3", "name": "language"}, {"value": "py_practice.py_allure_p", "name": "package"}], "status": "failed", "stop": 1605011566902, "testCaseId": "6b5468f4d278ea153ea5335a87add1b3", "name": "test_failure"}